### ISSUE TITLE
FlfMessage_Game.bin.txt中保留部分英文全大写的文本

### ISSUE THREAD

**Issue by wwylele** [wwylele/KEYTranslationProject#2]
因为这些文本涉及到不准备汉化的GameFontResult，因此不作翻译

**Comment by duangsuse** [comment]
...;-)

**Comment by duangsuse** [comment]
工具可不可以在linux平台上编译？

**Comment by wwylele** [comment]
@pigfromChina 除了 `brfnt/brfnt_mod/` 下的工具以外应该都可以（虽然我没有试过）。

`brfnt/brfnt_mod/` 不能在linux上编译是因为它在导入字体的时候用了windows API（导入方法很笨，先在一个bitmap上用字体写字，再把bitmap导入）。欢迎帮忙修改

另外，你这个问题应该发到新的issue里吧……
