### ISSUE TITLE
Crash on wii console

### ISSUE THREAD

**Issue by wwylele** [wwylele/KEYTranslationProject#4]
目前重构出来的ROM只能在模拟器上运行，在实机上会直接黑屏（~~只有一人测试过~~只有两人测试过，用硬盘引导的。求更多测试）
详细测试结果如下：
正常重构ROM（导入所有重构文本和字库），实机不能运行
仅修改FlfMessage_Game（用当前工具清空其所有文本，留下编号）导入ROM（不修改字库），实机不能运行
仅修改logo文件，实机可以运行
因此问题锁定在文本重构上

**Comment by wwylele** [comment]
测试更新：仅修改FlfMessage_Game的文本中的~~十个字母~~一个字母，依然会导致实机黑屏。

**Comment by wwylele** [comment]
测试更新：将FlfMessage_Game扩充长度（至16字节对齐），并修改尺寸标记，不更改文本。实机正常运行。

**Comment by duangsuse** [comment]
所以本issue该close了_(:з」∠)_

**Comment by wwylele** [comment]
@pigfromChina 我想你误解了。实际测试尚未通过

**Comment by wwylele** [comment]
搞清了，wiiscrubber的锅
